/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeStorage: typeof import('./components/CodeStorage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MediaAccess: typeof import('./components/MediaAccess.vue')['default']
    Pastebin: typeof import('./components/Pastebin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    TableEditor: typeof import('./components/TableEditor.vue')['default']
    TextEditor: typeof import('./components/TextEditor.vue')['default']
    Ui: typeof import('./components/ui.vue')['default']
  }
}
